### ISSUE TITLE
Deploy with Heroku

### ISSUE THREAD

**Issue by arnaudjnn** [lazurey/strapi-plugin-content-export-import#11]
I have the following error when trying to deploy with Heroku. What I forget?
```
Error: Module not found: Error: Can't resolve 'file-saver' in '/tmp/build_5841cb02_/plugins/content-export-import/admin/src/containers/ExportPage'
```

**Comment by lazurey** [comment]
I guess you need to run `yarn install` in the plugin folder.
`file-saver` is a dependency of this plugin.

**Comment by arnaudjnn** [comment]
Already done 😔

**Comment by SalahAdDin** [comment]
how did you do that?
i tried through ssh but i couldn't do that, can you help me @arnaudjnn ?

**Comment by SalahAdDin** [comment]
@arnaudjnn I don't know if you could solve it but I did in the following way:

- I added the library dependencies from the plugin to the project:
```json

    "file-saver": "^2.0.2",
    "pluralize": "^8.0.0",
    "strapi-helper-plugin": "^3.2.5"
```
- I installed it locally in order to update the `yarn.lock` package.
- Finally, I made a commit and I pushed it directly to **Heroku**.

That's enough.

**Comment by chloesun** [comment]
@SalahAdDin thanks for sharing your solution. Just to verify your process:
1, create `plugins` directory
2, `cd plugins`
3, `git submodule add https://github.com/lazurey/strapi-plugin-content-export-import.git plugins/content-export-import`
4, install those three dependencies at the root level
5 deploy to Heroku

Correct?

**Comment by chloesun** [comment]
@SalahAdDin  I tried and the folder structure looks like this, but after deployment, this plugin is still unavailable with Heroku. Anything wrong? Thanks!!
![module](https://user-images.githubusercontent.com/13730281/119560991-9fcf0c80-bd72-11eb-82ec-0402d966d6e4.PNG)
![gitmodule](https://user-images.githubusercontent.com/13730281/119560997-a198d000-bd72-11eb-8062-4057686e2739.PNG)

**Comment by SalahAdDin** [comment]
Did you try to re deploy it? I solved adding it as submodule; after deploying to `heroku`, it pulls the submodule itself and installs it.

**Comment by chloesun** [comment]
@SalahAdDin I set up the auto-deploy with Heroku, so technically after pushing to Github, it will redeploy. Here is my repo https://github.com/chloesun/ESDB_strapi, looks right to you? I still don't see that plugin installed in the production...

**Comment by SalahAdDin** [comment]
Try deployin it manually, your repository looks like mine, so, it is correct.

**Comment by chloesun** [comment]
@SalahAdDin thanks for your speedy reply, I even restart an app with Heroku, and manually deploy it, but still not showing this plugin.....

**Comment by SalahAdDin** [comment]
It is not normal, check when you deploy, and look the **Heroku** documentation as well.

**Comment by SalahAdDin** [comment]
It is missing your change on the repository, what it does is the same on local: it pulls the repository code before to build the admin panel: https://devcenter.heroku.com/articles/git-submodules#git-submodules, look it, specially the warning note.

**Comment by chloesun** [comment]
@SalahAdDin Thanks so much, I tried deploying with Heroku cli, and this time it worked! In the log, `remote: Cloning into 'plugins/content-export-import'...
remote: Submodule path 'plugins/content-export-import': checked out 'ccd9b9c933c70417db758ebb2e3c46028354cc78'
remote:
remote: Compressing source files... done.,` 
For some reason, I was deploying by connecting it to Github repo, and the Git submodules wasn't detected.

**Comment by SalahAdDin** [comment]
@chloesun It is because modules just works with direct pushes to _heroku_ (as the warning says).
